pub mod commands;
pub mod events;
pub mod window;

use tauri_specta::{collect_commands, collect_events, Builder, Commands};

macro_rules! collect_ipc_commands {
    ($($extra_command:tt)*) => {
        collect_commands![
            commands::app_health,
            commands::load_app_config,
            commands::save_app_config::<tauri::Wry>,
            commands::load_ui_preferences,
            commands::save_ui_preferences::<tauri::Wry>,
            commands::diagnostics_status,
            commands::set_diagnostics_enabled,
            commands::autostart_status,
            commands::set_autostart_enabled::<tauri::Wry>,
            commands::global_hotkey_status,
            commands::save_global_hotkeys::<tauri::Wry>,
            commands::generate_qr_code,
            commands::scan_screen_qr,
            commands::fetch_certificate,
            commands::calculate_certificate_sha256,
            commands::tun_request_elevation,
            commands::tun_revoke_elevation,
            commands::connect_active_profile::<tauri::Wry>,
            commands::disconnect_core::<tauri::Wry>,
            commands::restart_core::<tauri::Wry>,
            commands::runtime_status,
            commands::system_proxy_status,
            commands::set_system_proxy_mode::<tauri::Wry>,
            commands::tun_status,
            commands::tun_provider_diagnostics,
            commands::set_tun_enabled::<tauri::Wry>,
            commands::load_dns_settings,
            commands::save_dns_settings::<tauri::Wry>,
            commands::load_full_config_templates,
            commands::save_full_config_template::<tauri::Wry>,
            commands::list_profiles,
            commands::get_profile,
            commands::save_profile::<tauri::Wry>,
            commands::delete_profiles::<tauri::Wry>,
            commands::copy_profiles::<tauri::Wry>,
            commands::export_profile_share_links,
            commands::export_profile_share_links_base64,
            commands::export_profile_inner_links,
            commands::export_profile_client_config,
            commands::set_active_profile::<tauri::Wry>,
            commands::move_profile::<tauri::Wry>,
            commands::sort_profiles::<tauri::Wry>,
            commands::move_profiles_to_group::<tauri::Wry>,
            commands::dedupe_profiles::<tauri::Wry>,
            commands::list_group_child_candidates,
            commands::validate_group_profile,
            commands::preview_group_profile,
            commands::save_group_profile::<tauri::Wry>,
            commands::list_subscriptions,
            commands::get_subscription,
            commands::save_subscription::<tauri::Wry>,
            commands::delete_subscriptions::<tauri::Wry>,
            commands::import_profiles_from_text::<tauri::Wry>,
            commands::import_profiles_from_file::<tauri::Wry>,
            commands::update_subscriptions::<tauri::Wry>,
            commands::run_due_subscription_updates::<tauri::Wry>,
            commands::list_routings,
            commands::get_routing,
            commands::save_routing::<tauri::Wry>,
            commands::delete_routings::<tauri::Wry>,
            commands::set_active_routing::<tauri::Wry>,
            commands::save_routing_rule::<tauri::Wry>,
            commands::delete_routing_rules::<tauri::Wry>,
            commands::move_routing_rule::<tauri::Wry>,
            commands::import_config_template::<tauri::Wry>,
            commands::proxy_list_groups,
            commands::proxy_test_delay,
            commands::proxy_select_node::<tauri::Wry>,
            commands::proxy_list_connections,
            commands::proxy_close_connection::<tauri::Wry>,
            commands::proxy_set_traffic_mode::<tauri::Wry>,
            commands::proxy_reload_config::<tauri::Wry>,
            commands::proxy_start_monitor,
            commands::proxy_stop_monitor,
            commands::run_speedtest::<tauri::Wry>,
            commands::cancel_speedtest::<tauri::Wry>,
            commands::speedtest_status,
            commands::app_update_status::<tauri::Wry>,
            commands::record_app_update_diagnostic,
            commands::update_status,
            commands::save_update_preferences,
            commands::load_config_sources,
            commands::save_config_sources::<tauri::Wry>,
            commands::check_updates,
            commands::download_updates,
            commands::manual_app_update_links,
            commands::install_core_seed,
            window::get_window_chrome_config,
            window::open_settings_window::<tauri::Wry>,
            window::set_window_acrylic,
            $($extra_command)*
        ]
    };
}

#[cfg(debug_assertions)]
fn ipc_commands() -> Commands<tauri::Wry> {
    collect_ipc_commands![commands::ipc_demo_round_trip::<tauri::Wry>,]
}

#[cfg(not(debug_assertions))]
fn ipc_commands() -> Commands<tauri::Wry> {
    collect_ipc_commands![]
}

pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .typ::<voya_core::ProfileItem>()
        .typ::<voya_core::ProtocolExtraItem>()
        .typ::<voya_core::TransportExtraItem>()
        .typ::<voya_core::SubItem>()
        .typ::<voya_core::ImportProfilesResult>()
        .typ::<voya_core::SubscriptionUpdateResult>()
        .typ::<voya_core::RoutingItem>()
        .typ::<voya_core::RulesItem>()
        .typ::<voya_core::DnsItem>()
        .typ::<voya_app::dns::DnsSettings>()
        .typ::<voya_app::dns::DnsValidationIssue>()
        .typ::<voya_app::presets::ConfigTemplateSelection>()
        .typ::<voya_app::presets::ConfigTemplateImportResult>()
        .typ::<voya_app::proxy_runtime::ProxyGroupsSnapshot>()
        .typ::<voya_app::proxy_runtime::ProxyGroup>()
        .typ::<voya_app::proxy_runtime::ProxyNode>()
        .typ::<voya_app::proxy_runtime::ProxyDelayTestResult>()
        .typ::<voya_app::proxy_runtime::ProxyConnectionsSnapshot>()
        .typ::<voya_app::proxy_runtime::ProxyConnectionItem>()
        .typ::<voya_app::proxy_runtime::ProxyTrafficEvent>()
        .typ::<voya_app::proxy_runtime::ProxyMonitorState>()
        .typ::<voya_app::proxy_runtime::ProxyMonitorStatus>()
        .typ::<voya_app::speedtest::SpeedTestResult>()
        .typ::<voya_app::speedtest::SpeedtestRunResult>()
        .typ::<voya_app::speedtest::SpeedtestStatus>()
        .typ::<voya_app::updates::UpdateStatus>()
        .typ::<voya_app::updates::UpdateTarget>()
        .typ::<voya_app::updates::UpdateRunResult>()
        .typ::<voya_app::updates::UpdateCheckResult>()
        .typ::<voya_app::updates::ManualAppUpdateLinks>()
        .typ::<voya_app::updates::ManualAppUpdateDownload>()
        .typ::<voya_app::updates::UpdateTargetKind>()
        .typ::<voya_app::updates::UpdateAcquisition>()
        .typ::<voya_app::updates::UpdateResultStatus>()
        .typ::<voya_app::updates::ConfigSourceSettings>()
        .typ::<commands::UiPreferences>()
        .typ::<commands::UiThemeMode>()
        .typ::<commands::AppUpdateDiagnosticAction>()
        .typ::<commands::AppUpdateDiagnosticResult>()
        .typ::<voya_app::autostart::AutostartStatus>()
        .typ::<voya_app::autostart::AutostartPlatform>()
        .typ::<voya_app::hotkeys::HotkeyStatus>()
        .typ::<voya_app::hotkeys::GlobalHotkeyAction>()
        .typ::<voya_app::hotkeys::GlobalHotkeyBinding>()
        .typ::<voya_app::qr::QrCodeImage>()
        .typ::<voya_app::qr::QrScanResult>()
        .typ::<voya_app::qr::QrScanStatus>()
        .typ::<voya_app::certificates::CertificateFetchRequest>()
        .typ::<voya_app::certificates::CertificateFetchResult>()
        .typ::<voya_app::exports::ExportProfilesRequest>()
        .typ::<voya_app::exports::ExportProfilesResult>()
        .typ::<voya_app::exports::ExportProfilesFormat>()
        .typ::<voya_core::SpeedActionType>()
        .typ::<voya_app::tun::TunStatus>()
        .typ::<voya_app::tun::TunPreflight>()
        .typ::<voya_app::tun::TunProviderDiagnostics>()
        .typ::<voya_core::ProfileExItem>()
        .typ::<voya_core::ProfileListItem>()
        .typ::<voya_core::ProfileDedupeResult>()
        .typ::<voya_core::GroupChildCandidate>()
        .typ::<voya_core::GroupValidationResult>()
        .typ::<voya_core::GroupPreview>()
        .typ::<voya_core::GroupPreviewRoute>()
        .typ::<voya_core::GroupPreviewBalancer>()
        .typ::<voya_core::ProfileSortKey>()
        .typ::<voya_core::MoveAction>()
        .typ::<voya_core::FullConfigTemplateItem>()
        .typ::<voya_core::ServerStatItem>()
        .typ::<window::WindowChromeConfig>()
        .commands(ipc_commands())
        .events(collect_events![
            events::InvalidateEvent,
            events::TransientStreamEvent,
            events::AppEvent,
        ])
}
